[versions]
ant = "1.10.13"
aspose-words-cloud = "26.5.0"
commons-io = "2.22.0"
jmail = "2.0.2"
junit = "4.13.1"
okio = "1.17.6"

[libraries]
ant = { module = "org.apache.ant:ant", version.ref = "ant" }
aspose-words-cloud = { module = "com.aspose:aspose-words-cloud", version.ref = "aspose-words-cloud" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
jmail = { module = "com.sun.mail:jakarta.mail", version.ref = "jmail" } #override vulnerable version
junit = { module = "junit:junit", version.ref = "junit" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" } #override vulnerable version

[plugins]
jreleaser = { id = "org.jreleaser", version = "1.18.0" }
sonar = { id = "org.sonarqube", version = "7.1.0.6387" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }

